# Generated by Django 5.2.18 on 2026-10-06 15:25

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceProbe",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("correlation_id", models.UUIDField(default=uuid.uuid4)),
                (
                    "queue",
                    models.CharField(
                        choices=[("orders", "orders"), ("reports", "reports")], max_length=16
                    ),
                ),
                ("status", models.CharField(default="queued", editable=False, max_length=16)),
                ("worker_pid", models.PositiveIntegerField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["requested_by", "created_at"], name="core_servic_request_bf1ce0_idx"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("queue__in", ["orders", "reports"])),
                        name="probe_queue_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["queued", "succeeded"])),
                        name="probe_status_valid",
                    ),
                ],
            },
        ),
    ]
