# Generated by Django 5.2.18 on 2026-10-07 06:55

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="account_status",
            field=models.CharField(
                choices=[
                    ("active", "فعال"),
                    ("suspended", "تعلیق\u200cشده"),
                    ("closed", "بسته\u200cشده"),
                ],
                default="active",
                max_length=16,
                verbose_name="وضعیت حساب",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="base_currency",
            field=models.CharField(default="USDT", max_length=12, verbose_name="ارز پایه"),
        ),
        migrations.AddField(
            model_name="user",
            name="display_name",
            field=models.CharField(blank=True, max_length=80, verbose_name="نام نمایشی"),
        ),
        migrations.AddField(
            model_name="user",
            name="theme",
            field=models.CharField(
                choices=[("light", "روشن"), ("dark", "تیره")],
                default="light",
                max_length=8,
                verbose_name="ظاهر",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="timezone",
            field=models.CharField(
                default="Asia/Tehran", max_length=64, verbose_name="منطقه زمانی"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="ایمیل"),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                condition=models.Q(("email", ""), _negated=True),
                name="accounts_user_email_ci_unique",
            ),
        ),
    ]
