# Generated by Django 5.2.18 on 2026-10-07 07:06

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_passwordresetrequest_usersession"),
    ]

    operations = [
        migrations.CreateModel(
            name="TradingPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "default_order_amount",
                    models.DecimalField(
                        decimal_places=8,
                        default=Decimal("50"),
                        max_digits=20,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="مبلغ پیش\u200cفرض معامله",
                    ),
                ),
                (
                    "default_market",
                    models.CharField(
                        choices=[("spot", "Spot"), ("margin", "Margin")],
                        default="spot",
                        max_length=12,
                        verbose_name="بازار پیش\u200cفرض",
                    ),
                ),
                (
                    "tp1_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10"),
                        max_digits=5,
                        verbose_name="سهم TP1",
                    ),
                ),
                (
                    "tp2_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10"),
                        max_digits=5,
                        verbose_name="سهم TP2",
                    ),
                ),
                (
                    "tp3_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("80"),
                        max_digits=5,
                        verbose_name="سهم TP3",
                    ),
                ),
                (
                    "trailing_sl_enabled",
                    models.BooleanField(default=True, verbose_name="Trailing SL"),
                ),
                (
                    "trailing_tp_enabled",
                    models.BooleanField(default=True, verbose_name="Trailing TP"),
                ),
                (
                    "trailing_trigger",
                    models.CharField(
                        choices=[("tp1", "پس از TP1")],
                        default="tp1",
                        max_length=8,
                        verbose_name="شروع Trailing",
                    ),
                ),
                (
                    "trailing_distance_percent",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("1"),
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.001"))],
                        verbose_name="فاصله Trailing",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner",), name="one_trading_preferences_per_user"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("default_order_amount__gte", 0)),
                        name="trading_default_amount_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("tp1_percent__gte", 0),
                            ("tp2_percent__gte", 0),
                            ("tp3_percent__gte", 0),
                        ),
                        name="trading_tp_percentages_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("trailing_distance_percent__gt", 0)),
                        name="trading_trailing_distance_positive",
                    ),
                ],
            },
        ),
    ]
