# Generated by Django 5.2.18 on 2026-10-07 07:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_tradingpreferences"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        editable=False,
                        max_length=64,
                        validators=[django.core.validators.RegexValidator("^[a-z0-9_.-]+$")],
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict, editable=False)),
                ("ip_hash", models.CharField(blank=True, editable=False, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-pk"),
                "indexes": [
                    models.Index(
                        fields=["owner", "created_at"], name="accounts_au_owner_i_664c16_idx"
                    )
                ],
            },
        ),
    ]
